package it.cybsec.models;
// Generated 23 ott 2019, 14:32:06 by Hibernate Tools 5.4.2.Final

import java.util.*;
import javax.persistence.*;

/**
 * Dipendenti generated by hbm2java
 */
@Entity
@Table(name = "dipendenti")
public class Dipendente implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@ManyToOne
	@JoinColumn(name = "responsabile")
	private Dipendente responsabile;
	
	@ManyToOne
	@JoinColumn(name = "ruolo")
	private Ruolo ruolo;
	
	@ManyToOne
	@JoinColumn(name = "ufficio")
	private Ufficio ufficio;
	
	@Column(name = "nome")
	private String nome;
	
	@Column(name = "cognome")
	private String cognome;
	
	@OneToMany(mappedBy = "responsabile")
	private Set<Dipendente> dipendenti;

	public Dipendente() {
	}

	public Dipendente(Ruolo ruolo, Ufficio ufficio, String nome, String cognome) {
		this.ruolo = ruolo;
		this.ufficio = ufficio;
		this.nome = nome;
		this.cognome = cognome;
	}

	public Dipendente(Dipendente responsabile, Ruolo ruolo, Ufficio ufficio, String nome, String cognome, Set<Dipendente> dipendenti) {
		this.responsabile = responsabile;
		this.ruolo = ruolo;
		this.ufficio = ufficio;
		this.nome = nome;
		this.cognome = cognome;
		this.dipendenti = dipendenti;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Dipendente getResponsabile() {
		return this.responsabile;
	}

	public void setResponsabile(Dipendente responsabile) {
		this.responsabile = responsabile;
	}

	public Ruolo getRuolo() {
		return this.ruolo;
	}

	public void setRuolo(Ruolo ruolo) {
		this.ruolo = ruolo;
	}

	public Ufficio getUfficio() {
		return this.ufficio;
	}

	public void setUfficio(Ufficio ufficio) {
		this.ufficio = ufficio;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public Set<Dipendente> getDipendenti() {
		return this.dipendenti;
	}

	public void setDipendenti(Set<Dipendente> dipendenti) {
		this.dipendenti = dipendenti;
	}

}
