package it.cybsec.models;
// Generated 23 ott 2019, 14:32:06 by Hibernate Tools 5.4.2.Final

import java.util.*;
import javax.persistence.*;

/**
 * Ruoli generated by hbm2java
 */
@Entity
@Table(name = "ruoli")
public class Ruolo implements java.io.Serializable {

	private static final long serialVersionUID = 2L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name = "nome")
	private String nome;
	
	@OneToMany(mappedBy = "ruolo")
	private Set<Dipendente> dipendenti;

	public Ruolo() {
	}

	public Ruolo(String nome) {
		this.nome = nome;
	}

	public Ruolo(String nome, Set<Dipendente> dipendenti) {
		this.nome = nome;
		this.dipendenti = dipendenti;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Dipendente> getDipendenti() {
		return this.dipendenti;
	}

	public void setDipendenti(Set<Dipendente> dipendenti) {
		this.dipendenti = dipendenti;
	}

}
