package it.cybsec.models;
// Generated 23 ott 2019, 14:32:06 by Hibernate Tools 5.4.2.Final

import java.util.*;
import javax.persistence.*;

/**
 * Uffici generated by hbm2java
 */
@Entity
@Table(name = "uffici")
public class Ufficio implements java.io.Serializable {

	private static final long serialVersionUID = 3L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Column(name = "nome")
	private String nome;

	@Column(name = "dimensioni")
	private int dimensioni;
	
	@OneToMany(mappedBy = "ufficio")
	private Set<Dipendente> dipendenti;

	public Ufficio() {
	}

	public Ufficio(String nome, int dimensioni) {
		this.nome = nome;
		this.dimensioni = dimensioni;
	}

	public Ufficio(String nome, int dimensioni, Set<Dipendente> dipendenti) {
		this.nome = nome;
		this.dimensioni = dimensioni;
		this.dipendenti = dipendenti;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public int getDimensioni() {
		return this.dimensioni;
	}

	public void setDimensioni(int dimensioni) {
		this.dimensioni = dimensioni;
	}

	public Set<Dipendente> getDipendenti() {
		return this.dipendenti;
	}

	public void setDipendentis(Set<Dipendente> dipendenti) {
		this.dipendenti = dipendenti;
	}

}
